#!/bin/bash

set -ex

git clone https://github.com/UG-Team-Data-Science/rugllmlab.git
cd rugllmlab/rugllm_provider
pip install .

pip install codeium-jupyter

# Install required LaTeX packages
tlmgr install psnfss metafont mfware inconsolata tex ae parskip listings pgf preview \
    grfext epstopdf standalone luatex85 pgfplots geometry fancyhdr amsmath amssymb \
    hyperref graphicx xcolor enumerate enumitem inputenc fontenc titling longtable
