#!/bin/bash

set -ex

git clone https://github.com/UG-Team-Data-Science/rugllmlab.git
cd rugllmlab/rugllm_provider
pip install .

pip install codeium-jupyter

# Define custom installation directory
TINYTEX_DIR="/opt/tinytex"

# Install TinyTeX in the custom directory
wget -qO- "https://yihui.org/tinytex/install-bin-unix.sh" | env TINYTEX_INSTALLER_DIR="$TINYTEX_DIR" sh

# Update PATH to include TinyTeX binaries
echo "export PATH=$TINYTEX_DIR/bin:$PATH" >> /etc/profile
echo "export PATH=$TINYTEX_DIR/bin:$PATH" >> /etc/bash.bashrc

# Apply changes for the current session
export PATH="$TINYTEX_DIR/bin:$PATH"

# Ensure TinyTeX is working
tlmgr path add
